### ISSUE TITLE
Problemi con il template delle slide

### ISSUE THREAD

**Issue by giulianolatini** [CloudGenVR/Codegen2021Speakers#1]
Provo a scaricarlo ma quando PowerPoint lo apre mi chiede questo:
![image](https://user-images.githubusercontent.com/4264792/132235845-ed5e0152-527a-4a63-a157-6a6217c43085.png)
Concluso il Repair il file risulta vuoto.
Grazie in anticipo,

**Comment by andreatosato** [comment]
Ciao Giuliano,
A me lo mostra il PPTX. l'ho ricaricato per sicurezza e te lo metto anche qui
[Cloudgen2021_Template.pptx](https://github.com/CloudGenVR/Codegen2021Speakers/files/7117319/Cloudgen2021_Template.pptx)

**Comment by giulianolatini** [comment]
Ho capito il problema. É Google Chrome insieme a Ondrive che fanno pasticci.
Chrome apre il file in preview invece di scaricarlo. Se forzo lo scarico con il "Save link as" nella cartella Documenti Onedrive inizia subito a sincronizzarlo. Alla fine con un git clone ho risolto 👍 . Grazie :)

**Comment by giulianolatini** [comment]
Ho capito il problema. É Google Chrome insieme a Ondrive che fanno pasticci.
Chrome apre il file in preview invece di scaricarlo. Se forzo lo scarico con il "Save link as" nella cartella Documenti Onedrive inizia subito a sincronizzarlo. Alla fine con un git clone ho risolto 👍 . Grazie :)
